-- Optional Postgres / Supabase snippet: sync Kadam Haat after code changes.
-- Primary path: run `npm run db:import-featured-brands` (Prisma) which reads src/data/brand-requirements.ts.
--
-- If you already imported the old "Namaste- South Indian" featured row and want to repoint it:
-- 1) Find the user row (email was namastesouthindian@brand.com from import script).
-- 2) Update company name, industry, sizes, budget, locations, and must_have_amenities JSON.
--
-- Example (adjust user_id and JSON to match your schema):
--
-- UPDATE brand_profiles SET
--   company_name = 'Kadam Haat',
--   industry = 'Retail',
--   min_size = 1000,
--   max_size = 1200,
--   budget_min = 150000,
--   budget_max = 200000,
--   preferred_locations = '["Indiranagar"]'::jsonb,
--   must_have_amenities = jsonb_build_object(
--     'timeline', 'Immediate',
--     'storeType', 'Retail',
--     'targetAudience', 'Design-led shoppers, eco-conscious households, and interior-design clients seeking premium artisanal home and lifestyle products with natural materials.',
--     'additionalRequirements', 'Ground floor, Retail mix, High footfall, Bi-lanes acceptable'
--   )
-- WHERE user_id = '<BRAND_USER_UUID>';
