-- Clone property_location_cache from prop-017 → prop-018 (same micro-market / operator workaround for missing row).
-- Run in Supabase SQL editor. Adjust if your table has extra columns (e.g. intel_data) — add them to both lists.
-- Safe re-run: deletes prop-018 row first if you need to refresh.

-- DELETE FROM property_location_cache WHERE property_id = 'prop-018';

INSERT INTO property_location_cache (
  property_id,
  overall_score,
  daily_footfall,
  peak_hours,
  weekend_boost,
  competitors,
  competitor_count,
  complementary_brands,
  retail_mix,
  catchment,
  catchment_landmarks,
  saturation_level,
  market_summary,
  saturation_index,
  whitespace_score,
  demand_gap_score,
  market_potential_score,
  cannibalisation_risk,
  crowd_pullers,
  similar_markets,
  metro_name,
  metro_distance_m,
  bus_stops,
  affluence_indicator,
  total_households,
  rent_per_sqft,
  market_rent_low,
  market_rent_high,
  rent_data_source,
  nearest_area_key,
  resolved_lat,
  resolved_lng,
  cached_at,
  cache_expires_at,
  data_quality,
  source
)
SELECT
  'prop-018',
  overall_score,
  daily_footfall,
  peak_hours,
  weekend_boost,
  competitors,
  competitor_count,
  complementary_brands,
  retail_mix,
  catchment,
  catchment_landmarks,
  saturation_level,
  market_summary,
  saturation_index,
  whitespace_score,
  demand_gap_score,
  market_potential_score,
  cannibalisation_risk,
  crowd_pullers,
  similar_markets,
  metro_name,
  metro_distance_m,
  bus_stops,
  affluence_indicator,
  total_households,
  rent_per_sqft,
  market_rent_low,
  market_rent_high,
  rent_data_source,
  nearest_area_key,
  resolved_lat,
  resolved_lng,
  NOW(),
  cache_expires_at,
  data_quality,
  source
FROM property_location_cache
WHERE property_id = 'prop-017'
ON CONFLICT (property_id) DO UPDATE SET
  overall_score = EXCLUDED.overall_score,
  daily_footfall = EXCLUDED.daily_footfall,
  peak_hours = EXCLUDED.peak_hours,
  weekend_boost = EXCLUDED.weekend_boost,
  competitors = EXCLUDED.competitors,
  competitor_count = EXCLUDED.competitor_count,
  complementary_brands = EXCLUDED.complementary_brands,
  retail_mix = EXCLUDED.retail_mix,
  catchment = EXCLUDED.catchment,
  catchment_landmarks = EXCLUDED.catchment_landmarks,
  saturation_level = EXCLUDED.saturation_level,
  market_summary = EXCLUDED.market_summary,
  saturation_index = EXCLUDED.saturation_index,
  whitespace_score = EXCLUDED.whitespace_score,
  demand_gap_score = EXCLUDED.demand_gap_score,
  market_potential_score = EXCLUDED.market_potential_score,
  cannibalisation_risk = EXCLUDED.cannibalisation_risk,
  crowd_pullers = EXCLUDED.crowd_pullers,
  similar_markets = EXCLUDED.similar_markets,
  metro_name = EXCLUDED.metro_name,
  metro_distance_m = EXCLUDED.metro_distance_m,
  bus_stops = EXCLUDED.bus_stops,
  affluence_indicator = EXCLUDED.affluence_indicator,
  total_households = EXCLUDED.total_households,
  rent_per_sqft = EXCLUDED.rent_per_sqft,
  market_rent_low = EXCLUDED.market_rent_low,
  market_rent_high = EXCLUDED.market_rent_high,
  rent_data_source = EXCLUDED.rent_data_source,
  nearest_area_key = EXCLUDED.nearest_area_key,
  resolved_lat = EXCLUDED.resolved_lat,
  resolved_lng = EXCLUDED.resolved_lng,
  cached_at = EXCLUDED.cached_at,
  cache_expires_at = EXCLUDED.cache_expires_at,
  data_quality = EXCLUDED.data_quality,
  source = EXCLUDED.source;
