import type { Metadata } from 'next'
import { getPrisma } from '@/lib/get-prisma'
import { decodePropertySlug } from '@/lib/property-slug'

const SITE_URL = 'https://lokazen.in'

/** Formats price for human-readable display in OG tags */
function formatPrice(price: number, priceType: string, size: number): string {
  if (priceType === 'sqft') {
    const monthly = size * price
    if (monthly >= 100000) return `₹${(monthly / 100000).toFixed(1)}L/mo`
    return `₹${monthly.toLocaleString('en-IN')}/mo`
  }
  if (price >= 100000) return `₹${(price / 100000).toFixed(1)}L/mo`
  return `₹${price.toLocaleString('en-IN')}/mo`
}

/**
 * Returns the first valid HTTP image URL from a property's images array,
 * skipping placeholder/localhost/stock photo URLs.
 */
function getFirstValidImage(images: unknown): string | null {
  if (!Array.isArray(images)) return null
  for (const img of images) {
    if (typeof img !== 'string' || !img.trim()) continue
    const src = img.trim()
    if (
      src.startsWith('http') &&
      !src.includes('localhost') &&
      !src.includes('unsplash') &&
      !src.startsWith('/images/')
    ) {
      return src
    }
  }
  return null
}

/**
 * Builds the URL for the dynamic OG image generated by /api/og.
 * This is the branded property card shown when sharing on WhatsApp,
 * LinkedIn, Twitter/X, and any other platform that reads og:image.
 */
function buildOgImageUrl(params: {
  title: string
  city: string
  price: string
  size: string
  type: string
  address: string
}): string {
  const qs = new URLSearchParams({
    title: params.title.slice(0, 80),
    city: params.city,
    price: params.price,
    size: params.size,
    type: params.type,
    address: params.address.slice(0, 60),
  })
  return `${SITE_URL}/api/og?${qs.toString()}`
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>
}): Promise<Metadata> {
  const { id: slug } = await params
  const propertyId = decodePropertySlug(slug)

  // Canonical URL for this property (used as og:url and alternates.canonical)
  const canonicalUrl = `${SITE_URL}/properties/${slug}/match`

  const prisma = await getPrisma()
  if (!prisma) {
    return {
      title: 'Property | Lokazen',
      alternates: { canonical: canonicalUrl },
      openGraph: {
        title: 'Property | Lokazen',
        url: canonicalUrl,
        images: [`${SITE_URL}/lokazen-social.png`],
      },
    }
  }

  let property: {
    title: string
    description: string | null
    address: string
    city: string
    size: number
    price: unknown
    priceType: string
    propertyType: string
    images: unknown
  } | null = null

  try {
    property = await prisma.property.findUnique({
      where: { id: propertyId },
      select: {
        title: true,
        description: true,
        address: true,
        city: true,
        size: true,
        price: true,
        priceType: true,
        propertyType: true,
        images: true,
      },
    })
  } catch {
    // Fallback on DB error
  }

  if (!property) {
    return {
      title: 'Property | Lokazen',
      alternates: { canonical: canonicalUrl },
      openGraph: {
        title: 'Property | Lokazen',
        url: canonicalUrl,
        images: [`${SITE_URL}/lokazen-social.png`],
      },
    }
  }

  // ── Data extraction ──────────────────────────────────────────────────────
  const price =
    typeof property.price === 'object' &&
    property.price !== null &&
    'toNumber' in property.price
      ? (property.price as { toNumber: () => number }).toNumber()
      : Number(property.price) || 0

  const priceStr = formatPrice(price, property.priceType, property.size)
  const location = `${property.address}, ${property.city}`
  const shortDesc = `${property.size.toLocaleString()} sqft · ${priceStr} · ${location}`

  const ogTitle = `${property.title} | Lokazen`
  const ogDescription = property.description
    ? `${property.description.slice(0, 155)}${property.description.length > 155 ? '…' : ''}`
    : shortDesc

  // ── OG image strategy ────────────────────────────────────────────────────
  // Primary: branded dynamic card generated by /api/og (always reliable, branded)
  // Secondary: actual property photo (shown as additional image for platforms that support it)
  const dynamicOgImage = buildOgImageUrl({
    title: property.title,
    city: property.city,
    price: priceStr,
    size: String(property.size),
    type: property.propertyType || 'other',
    address: property.address,
  })

  const propertyPhoto = getFirstValidImage(property.images)

  // Build images array: dynamic card first (guaranteed quality), then actual photo
  const ogImages: { url: string; width: number; height: number; alt: string; type: string }[] = [
    {
      url: dynamicOgImage,
      width: 1200,
      height: 630,
      alt: property.title,
      type: 'image/png',
    },
  ]

  // Add the real property photo as a second image when available
  // (some platforms like Slack/LinkedIn may cycle through multiple images)
  if (propertyPhoto) {
    ogImages.push({
      url: propertyPhoto,
      width: 1200,
      height: 630,
      alt: `${property.title} — ${property.city}`,
      type: propertyPhoto.match(/\.jpe?g/i) ? 'image/jpeg' : 'image/png',
    })
  }

  return {
    title: ogTitle,
    description: ogDescription,
    alternates: {
      canonical: canonicalUrl,
    },
    openGraph: {
      title: ogTitle,
      description: ogDescription,
      url: canonicalUrl,
      siteName: 'Lokazen',
      type: 'website',
      locale: 'en_IN',
      images: ogImages,
    },
    twitter: {
      card: 'summary_large_image',
      title: ogTitle,
      description: ogDescription,
      images: [dynamicOgImage],
    },
  }
}

export default function PropertyLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>{children}</>
}
