import type { Metadata } from 'next'
import { getPrisma } from '@/lib/get-prisma'
import { decodePropertySlug } from '@/lib/property-slug'

const SITE_URL = 'https://lokazen.in'

/** Formats price for human-readable display in OG tags */
function formatPrice(price: number, priceType: string, size: number): string {
  if (priceType === 'sqft') {
    const monthly = size * price
    if (monthly >= 100000) return `₹${(monthly / 100000).toFixed(1)}L/mo`
    return `₹${monthly.toLocaleString('en-IN')}/mo`
  }
  if (price >= 100000) return `₹${(price / 100000).toFixed(1)}L/mo`
  return `₹${price.toLocaleString('en-IN')}/mo`
}

/**
 * Extracts a URL string from an image entry which may be:
 *  - a plain URL string
 *  - an object with a `url`, `src`, or `href` property
 */
function extractUrl(img: unknown): string | null {
  if (typeof img === 'string') return img.trim() || null
  if (img && typeof img === 'object') {
    const obj = img as Record<string, unknown>
    const raw = obj.url ?? obj.src ?? obj.href ?? obj.image ?? null
    return typeof raw === 'string' ? raw.trim() || null : null
  }
  return null
}

/**
 * Returns the first valid HTTP image URL from a property's images field.
 * Handles plain string arrays, arrays of URL objects, and JSON-encoded strings.
 * Skips placeholder, localhost, and stock photo URLs.
 */
function getFirstValidImage(images: unknown): string | null {
  let arr: unknown[] = []

  if (Array.isArray(images)) {
    arr = images
  } else if (typeof images === 'string') {
    // Sometimes JSONB comes back as a raw JSON string
    try {
      const parsed = JSON.parse(images)
      if (Array.isArray(parsed)) arr = parsed
    } catch {
      // single URL string stored directly
      arr = [images]
    }
  }

  for (const img of arr) {
    const src = extractUrl(img)
    if (!src) continue
    if (
      src.startsWith('http') &&
      !src.includes('localhost') &&
      !src.includes('unsplash') &&
      !src.startsWith('/images/')
    ) {
      return src
    }
  }
  return null
}

/**
 * Builds the URL for the dynamic OG image generated by /api/og.
 * This is the branded property card shown when sharing on WhatsApp,
 * LinkedIn, Twitter/X, and any other platform that reads og:image.
 */
function buildOgImageUrl(params: {
  title: string
  city: string
  price: string
  size: string
  type: string
  address: string
}): string {
  const qs = new URLSearchParams({
    title: params.title.slice(0, 80),
    city: params.city,
    price: params.price,
    size: params.size,
    type: params.type,
    address: params.address.slice(0, 60),
  })
  return `${SITE_URL}/api/og?${qs.toString()}`
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>
}): Promise<Metadata> {
  const { id: slug } = await params
  const propertyId = decodePropertySlug(slug)

  // Canonical URL for this property (used as og:url and alternates.canonical)
  const canonicalUrl = `${SITE_URL}/properties/${slug}/match`

  const prisma = await getPrisma()
  if (!prisma) {
    return {
      title: 'Property | Lokazen',
      alternates: { canonical: canonicalUrl },
      openGraph: {
        title: 'Property | Lokazen',
        url: canonicalUrl,
        images: [`${SITE_URL}/opengraph-image`],
      },
    }
  }

  let property: {
    title: string
    description: string | null
    address: string
    city: string
    size: number
    price: unknown
    priceType: string
    propertyType: string
    images: unknown
  } | null = null

  try {
    property = await prisma.property.findUnique({
      where: { id: propertyId },
      select: {
        title: true,
        description: true,
        address: true,
        city: true,
        size: true,
        price: true,
        priceType: true,
        propertyType: true,
        images: true,
      },
    })
  } catch {
    // Fallback on DB error
  }

  if (!property) {
    return {
      title: 'Property | Lokazen',
      alternates: { canonical: canonicalUrl },
      openGraph: {
        title: 'Property | Lokazen',
        url: canonicalUrl,
        images: [`${SITE_URL}/opengraph-image`],
      },
    }
  }

  // ── Data extraction ──────────────────────────────────────────────────────
  const price =
    typeof property.price === 'object' &&
    property.price !== null &&
    'toNumber' in property.price
      ? (property.price as { toNumber: () => number }).toNumber()
      : Number(property.price) || 0

  const priceStr = formatPrice(price, property.priceType, property.size)
  const location = `${property.address}, ${property.city}`
  const shortDesc = `${property.size.toLocaleString()} sqft · ${priceStr} · ${location}`

  const ogTitle = `${property.title} | Lokazen`
  const ogDescription = property.description
    ? `${property.description.slice(0, 155)}${property.description.length > 155 ? '…' : ''}`
    : shortDesc

  // ── OG image strategy ────────────────────────────────────────────────────
  // Priority 1: actual property photo — real image scrapers/WhatsApp will show
  // Priority 2: dynamic branded card from /api/og — fallback when no valid photo
  const dynamicOgImage = buildOgImageUrl({
    title: property.title,
    city: property.city,
    price: priceStr,
    size: String(property.size),
    type: property.propertyType || 'other',
    address: property.address,
  })

  const propertyPhoto = getFirstValidImage(property.images)

  // If the property has a real photo, use it as the primary OG image.
  // The dynamic card is added as a second entry (fallback for platforms that
  // render multiple images, and used by Twitter which reads the first entry).
  const primaryOgImage = propertyPhoto ?? dynamicOgImage

  const ogImages: { url: string; width: number; height: number; alt: string; type: string }[] = [
    {
      url: primaryOgImage,
      width: 1200,
      height: 630,
      alt: property.title,
      type: primaryOgImage.match(/\.jpe?g/i) ? 'image/jpeg' : 'image/png',
    },
  ]

  // Always include the generated card as a second image so platforms
  // that support multiple images (Slack, LinkedIn) also show branded context.
  if (propertyPhoto) {
    ogImages.push({
      url: dynamicOgImage,
      width: 1200,
      height: 630,
      alt: `${property.title} — ${property.city} · Lokazen`,
      type: 'image/png',
    })
  }

  return {
    title: ogTitle,
    description: ogDescription,
    alternates: {
      canonical: canonicalUrl,
    },
    openGraph: {
      title: ogTitle,
      description: ogDescription,
      url: canonicalUrl,
      siteName: 'Lokazen',
      type: 'website',
      locale: 'en_IN',
      images: ogImages,
    },
    twitter: {
      card: 'summary_large_image',
      title: ogTitle,
      description: ogDescription,
      images: [primaryOgImage],
    },
  }
}

export default function PropertyLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>{children}</>
}
