/**
 * Seed AreaGrowthPatterns for 2026 projections
 * Run: npm run db:seed-growth
 */

import { PrismaClient } from '@prisma/client'
import { config } from 'dotenv'
import { resolve } from 'path'

config({ path: resolve(__dirname, '../.env.local') })

const prisma = new PrismaClient()

const bangaloreGrowthPatterns = [
  {
    area: 'Indiranagar',
    populationGrowth: 1.8,
    incomeGrowth: 7.2,
    youth18_34Trend: -2.0,
    senior65PlusTrend: 1.0,
    workingPopTrend: 1.2,
    highIncomeGrowth: 8.5,
    middleClassGrowth: 4.0,
    vehicleOwnership: 3.0,
    diningOutGrowth: 6.0,
    healthConsciousness: 5.0,
    digitalAdoption: 12.0,
    newMetroStations: 0,
    roadExpansion: false,
    mallDevelopment: 0,
    techParkGrowth: false,
    rentAppreciation: 5.5,
    propertyPriceGrowth: 5.5,
    commercialSupply: 4.0,
    newBusinessGrowth: 4.2,
    chainExpansion: 2.5,
    cloudKitchenGrowth: 6.0,
    dataSource: 'Census 2021 + Projection Model',
    projectionConfidence: 0.85,
  },
  {
    area: 'Koramangala',
    populationGrowth: 2.2,
    incomeGrowth: 8.0,
    youth18_34Trend: 3.0,
    senior65PlusTrend: 0.5,
    workingPopTrend: 2.5,
    highIncomeGrowth: 9.0,
    middleClassGrowth: 4.5,
    vehicleOwnership: 3.5,
    diningOutGrowth: 7.5,
    healthConsciousness: 5.5,
    digitalAdoption: 15.0,
    newMetroStations: 0,
    roadExpansion: false,
    mallDevelopment: 1,
    techParkGrowth: true,
    rentAppreciation: 6.0,
    propertyPriceGrowth: 6.0,
    commercialSupply: 5.0,
    newBusinessGrowth: 6.5,
    chainExpansion: 3.0,
    cloudKitchenGrowth: 18.0,
    dataSource: 'Census 2021 + Projection Model',
    projectionConfidence: 0.9,
  },
  {
    area: 'Whitefield',
    populationGrowth: 4.5,
    incomeGrowth: 7.5,
    youth18_34Trend: 5.0,
    senior65PlusTrend: 0.3,
    workingPopTrend: 4.0,
    highIncomeGrowth: 10.0,
    middleClassGrowth: 5.0,
    vehicleOwnership: 5.0,
    diningOutGrowth: 8.0,
    healthConsciousness: 5.0,
    digitalAdoption: 14.0,
    newMetroStations: 2,
    roadExpansion: true,
    mallDevelopment: 3,
    techParkGrowth: true,
    rentAppreciation: 7.0,
    propertyPriceGrowth: 7.0,
    commercialSupply: 8.0,
    newBusinessGrowth: 8.0,
    chainExpansion: 4.0,
    cloudKitchenGrowth: 15.0,
    dataSource: 'Census 2021 + Projection Model',
    projectionConfidence: 0.8,
  },
  {
    area: 'HSR Layout',
    populationGrowth: 3.0,
    incomeGrowth: 7.8,
    youth18_34Trend: 4.0,
    senior65PlusTrend: 0.4,
    workingPopTrend: 3.0,
    highIncomeGrowth: 8.0,
    middleClassGrowth: 4.5,
    vehicleOwnership: 4.0,
    diningOutGrowth: 7.0,
    healthConsciousness: 6.5,
    digitalAdoption: 13.0,
    newMetroStations: 1,
    roadExpansion: true,
    mallDevelopment: 2,
    techParkGrowth: false,
    rentAppreciation: 6.5,
    propertyPriceGrowth: 6.5,
    commercialSupply: 6.0,
    newBusinessGrowth: 7.0,
    chainExpansion: 3.0,
    cloudKitchenGrowth: 12.0,
    dataSource: 'Census 2021 + Projection Model',
    projectionConfidence: 0.82,
  },
  {
    area: 'JP Nagar',
    populationGrowth: 2.5,
    incomeGrowth: 6.0,
    youth18_34Trend: 1.0,
    senior65PlusTrend: 1.2,
    workingPopTrend: 2.0,
    highIncomeGrowth: 5.0,
    middleClassGrowth: 5.0,
    vehicleOwnership: 3.5,
    diningOutGrowth: 5.5,
    healthConsciousness: 4.0,
    digitalAdoption: 10.0,
    newMetroStations: 1,
    roadExpansion: false,
    mallDevelopment: 1,
    techParkGrowth: false,
    rentAppreciation: 4.5,
    propertyPriceGrowth: 4.5,
    commercialSupply: 4.0,
    newBusinessGrowth: 5.0,
    chainExpansion: 2.0,
    cloudKitchenGrowth: 8.0,
    dataSource: 'Census 2021 + Projection Model',
    projectionConfidence: 0.78,
  },
  {
    area: 'BTM Layout',
    populationGrowth: 3.2,
    incomeGrowth: 6.5,
    youth18_34Trend: 3.5,
    senior65PlusTrend: 0.5,
    workingPopTrend: 2.8,
    highIncomeGrowth: 6.5,
    middleClassGrowth: 5.5,
    vehicleOwnership: 4.5,
    diningOutGrowth: 6.5,
    healthConsciousness: 4.5,
    digitalAdoption: 11.0,
    newMetroStations: 0,
    roadExpansion: true,
    mallDevelopment: 1,
    techParkGrowth: false,
    rentAppreciation: 5.0,
    propertyPriceGrowth: 5.0,
    commercialSupply: 5.0,
    newBusinessGrowth: 6.0,
    chainExpansion: 2.5,
    cloudKitchenGrowth: 14.0,
    dataSource: 'Census 2021 + Projection Model',
    projectionConfidence: 0.76,
  },
  {
    area: 'Jayanagar',
    populationGrowth: 2.0,
    incomeGrowth: 5.5,
    youth18_34Trend: 0.5,
    senior65PlusTrend: 1.5,
    workingPopTrend: 1.5,
    highIncomeGrowth: 4.5,
    middleClassGrowth: 4.5,
    vehicleOwnership: 2.5,
    diningOutGrowth: 5.0,
    healthConsciousness: 4.0,
    digitalAdoption: 9.0,
    newMetroStations: 1,
    roadExpansion: false,
    mallDevelopment: 0,
    techParkGrowth: false,
    rentAppreciation: 4.0,
    propertyPriceGrowth: 4.0,
    commercialSupply: 3.0,
    newBusinessGrowth: 4.0,
    chainExpansion: 1.5,
    cloudKitchenGrowth: 6.0,
    dataSource: 'Census 2021 + Projection Model',
    projectionConfidence: 0.75,
  },
]

async function seedGrowthPatterns() {
  for (const pattern of bangaloreGrowthPatterns) {
    const wardId = `WARD_${pattern.area.toUpperCase().replace(/\s+/g, '_')}`
    await prisma.areaGrowthPatterns.upsert({
      where: { wardId },
      update: pattern,
      create: { wardId, ...pattern },
    })
  }
  console.log('Growth patterns seeded for', bangaloreGrowthPatterns.length, 'areas')
}

seedGrowthPatterns()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e)
    prisma.$disconnect()
    process.exit(1)
  })
